version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: opensid-postgres
    environment:
      POSTGRES_DB: opensid
      POSTGRES_USER: opensid
      POSTGRES_PASSWORD: opensid123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opensid-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: opensid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - opensid-network

  # MinIO for object storage (S3 compatible)
  minio:
    image: minio/minio:latest
    container_name: opensid-minio
    environment:
      MINIO_ROOT_USER: opensid
      MINIO_ROOT_PASSWORD: opensid123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - opensid-network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: opensid-adminer
    ports:
      - "8080:8080"
    networks:
      - opensid-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  opensid-network:
    driver: bridge